### PR TITLE
Refactor data validations for controllers in backend - Draft_1

### PR DESCRIPTION
**Pull request by eulerbutcooler**
- Created a separate file for validation checks.
- Improved error handling

### CODE REVIEW

**Review by erenfn — CHANGES_REQUESTED** [review]
If validations fail, we should return an appropriate message. Right now, it returns Internal Server Error -I tried it with an invalid email.

**Comment by eulerbutcooler** [comment]
fixing it right away

**Comment by eulerbutcooler** [comment]
@erenfn can you check once? i tried it without making any changes to my current code and it returned descriptive errors.
Including the screenshots of postman here - 
Email handling
Password handling
Returned 201

**Comment by erenfn** [comment]
Yep, they work. In errors, can you just include message, and delete other fields (type, value, path, location)?

**Review by erenfn — CHANGES_REQUESTED** [review]
Currently, in the frontend, we assume that only one error message is returned. Can you make the necessary changes to handle multiple error messages?

The Auth pages are under src/scenes/login

This is what we have right now:
```
      if (error.response?.data?.error) {
        setErrorMessage(error.response.data.error);
      }
      else {
        setErrorMessage('An error occurred. Please try again.');
      }
```

**Comment by eulerbutcooler** [comment]
> Currently, in the frontend, we assume that only one error message is returned. Can you make the necessary changes to handle multiple error messages?
> 
> The Auth pages are under src/scenes/login
> 
> This is what we have right now:
> 
> ```
>       if (error.response?.data?.error) {
>         setErrorMessage(error.response.data.error);
>       }
>       else {
>         setErrorMessage('An error occurred. Please try again.');
>       }
> ```

on it!

**Comment by eulerbutcooler** [comment]
@erenfn shouldn't we keep some abstraction in what the user sees in an error? it wouldn't be a good idea to tell the user if their email and password both are invalid when they try to login. we should just display the first error that occurs i think.
let me know your thoughts.
also is there any slack/discord channel where we can discuss about code?

**Comment by erenfn** [comment]
> @erenfn also is there any slack/discord channel where we can discuss about code? communicating here isn't efficient i feel.

@gorkem-bwl

**Comment by erenfn** [comment]
And -I just saw your deleted message- it would be better if we just return the first error; that way, we won't have to change the frontend.

**Comment by gorkem-bwl** [comment]
> @erenfn also is there any slack/discord channel where we can discuss about code? communicating here isn't efficient i feel.

Currently, we don't have one for outside contributors but feel free to send @erenfn your Discord username and exchange information there.

**Comment by eulerbutcooler** [comment]
@erenfn could be pls add me on discord it'll be better for communicating - eulerbutcooler#4673

**Review by uparkalau — CHANGES_REQUESTED** [review]
Review Coderabbit recommendations

**Review by eulerbutcooler — COMMENTED** [review]
reviewed to the best of my knowledge but lemme know if i need to make any changes

**Comment by erenfn** [comment]
I'm closing it for now, as there are many merge conflicts. You can reopen this PR after merging/rebasing and finishing up the a group of validations

**Pull request closed without merging**
