### PR TITLE
feat: Adding a utility function to make settings rbac

### LINKED ISSUE #338: Settings RBAC
- [ ] Create a helper function to check role based authentications
- [ ] Refactor changes made in #337 such as `{role === 'admin' && <ParagraphCSS />}` to use this function. 
- [ ] Team and API Key options in settings page should be only visible to the admins not members

image
image

### PR DESCRIPTION
**Pull request by aryanp-86**
Closes #338 
### Implement Role-Based Access Control for Settings Page
This PR adds a utility function hasRolePermission to handle role-based authorizations:
```
export function hasRolePermission(userRole, requiredRole) {
    if (!userRole || !requiredRole) return false;
    return userRole === requiredRole;
}
```

- Updated the Settings page to enforce RBAC, restricting access to the "Team" and "API" sections to users with an admin role.
- Refactored code across the codebase (including in PR #337) to consistently use the hasRolePermission function for authorization checks

### CODE REVIEW

**Review by erenfn — CHANGES_REQUESTED** [review]
Add a prop to the function which is a react element, and return that element if user has permission

For example, from

`{hasRolePermission(role, 'admin') && <ParagraphCSS />}`

to

`hasRolePermission(role, 'admin', <ParagraphCSS />)`

**Review by erenfn — CHANGES_REQUESTED** [review]
One last thing: When you change your role from admin to member (this is a very rare case, but still), the 'team' and 'API key & code' sections should disappear immediately after the role change.

image

**Comment by aryanp-86** [comment]
Actually Settings page and team tab fetch user data differently which was causing the issue. I have implemented code in team tab role change handler so that userInfo updates automatically.

**Review by erenfn — CHANGES_REQUESTED** [review]
```
MUI: The `value` provided to the Tabs component is invalid.
None of the Tabs' children match with "3".
You can provide one of the following values: 1, 2.
```

After changing your role from admin to member, this error appears in the console. Can we manually set the tab number after this role change?

**Comment by erenfn** [comment]
Can we remove that useEffect in Settings page and handle tab change after role change in Teams page?

Also using useReducer can be better when handling this error to change role and tab at the same time

**Comment by aryanp-86** [comment]
Yeah that would be better. I will do the changes.

**Review by erenfn — CHANGES_REQUESTED** [review]
The tab value shouldn't be placed in the authProvider. You can simply pass it down as a prop.

**Pull request merged**
