### PR TITLE
match local host db variable in config with .env

### PR DESCRIPTION
**Pull request by parthmanhas**

### CODE REVIEW

**Comment by erenfn** [comment]
did you test this?

```
bluewave-onboarding-onboarding_backend-1  | Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
bluewave-onboarding-onboarding_backend-1  | Error syncing models: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
```

**Comment by parthmanhas** [comment]
> did you test this? I get this error
> 
> ```
> bluewave-onboarding-onboarding_backend-1  | Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
> bluewave-onboarding-onboarding_backend-1  | Error syncing models: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
> ```

yes, this seems to be working in my local setup, I am not running a docker container though
image

**Comment by erenfn** [comment]
try it with docker

**Comment by parthmanhas** [comment]
works in docker. My bad 😅

**Pull request closed without merging**
