### PR TITLE
#1 Define colors, text, menu icons and popup menu 

### PR DESCRIPTION
**Pull request by SimerdeepSinghGrewal**
I've added Drop down with search, Selectable drop downs, Implemented menu and menu icons, Implemented popover menu.
firstlty implemented dropdown search in this branch "dropdown-search"
then added menu and icons in this branch "menu+icons"
and finally added the popover menu and the customize button for table in this branch "table+customise+menu"

### CODE REVIEW

**Comment by swoopertr** [comment]
Hi Simerdeep, you could separate down some long coded components like Table.jsx, SideBar.jsx,
and some of the SVGs can be another file to import.

**Comment by SimerdeepSinghGrewal** [comment]
> Hi Simerdeep, you could separate down some long coded components like Table.jsx, SideBar.jsx, and some of the SVGs can be another file to import.

Hi Tunc ,
thank you for the input. I wanted to know if I can replace the SVG's with MUI Icons ? like the shape will be lil different but code will be very short as compared to current version.

**Review by uparkalau — COMMENTED** [review]
Yes you can use Mui icons.

**Comment by SimerdeepSinghGrewal** [comment]
@swoopertr @uparkalau I did replaced the svg with MUI icons , code looks neat but please have a look and advice if I need to do anything further. 
I reduced the code size of table.jsx also.

**Comment by uparkalau** [comment]
fetch develop branch before merging

**Review by uparkalau — APPROVED** [review]

**Pull request merged**
