### PR TITLE
Fix/379 button design in the home page

### PR DESCRIPTION
**Pull request by MandeepPaul**
## Describe your changes

Changed the button UI on homepage

## Issue number

#379 

## Please ensure all items are checked off before requesting a review:

- [ ] I deployed the code locally.
- [ ] I have performed a self-review of my code.
- [ ] I have included the issue # in the PR.
- [ ] I have labelled the PR correctly.
- [ ] The issue I am working on is assigned to me.
- [ ] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [ ] I made sure font sizes, color choices etc are all referenced from the theme.
- [ ] My PR is granular and targeted to one specific feature.
- [ ] I took a screenshot or a video and attached to this PR if there is a UI change.

## Before
Screenshot 2024-12-17 041754

## After
Screenshot 2024-12-17 041735

### CODE REVIEW

**Review by erenfn — CHANGES_REQUESTED** [review]
I couldn't remember if I mentioned it but, we are working on the develop branch. So can you change the target branch to `develop `from `master`?

**Comment by erenfn** [comment]
@gorkem-bwl @bolatein any comments about the UI?

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl @bolatein any comments about the UI?

Neither colors nor wording are not the same. They must be same as in Figma.

image

**Comment by MandeepPaul** [comment]
Noted! I will update right right away

**Comment by gorkem-bwl** [comment]
> Noted! I will update right away

Make sure you compare them side-by-side and then open your PR.

**Comment by MandeepPaul** [comment]
I have created a new PR (#398) with the correct target branch to ensure proper integration.

**Pull request closed without merging**
