### PR TITLE
updated dashboard buttons link

### PR DESCRIPTION
**Pull request by MandeepPaul**
## Describe your changes

Changed target links for buttons on dashboard

## Issue number

#428 

## Please ensure all items are checked off before requesting a review:

- [ ] I deployed the code locally.
- [ ] I have performed a self-review of my code.
- [ ] I have included the issue # in the PR.
- [ ] I have labelled the PR correctly.
- [ ] The issue I am working on is assigned to me.
- [ ] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [ ] I made sure font sizes, color choices etc are all referenced from the theme.
- [ ] My PR is granular and targeted to one specific feature.
- [ ] I took a screenshot or a video and attached to this PR if there is a UI change.

### CODE REVIEW

**Review by erenfn — CHANGES_REQUESTED** [review]
It should also open the 'create' page' dialog. use useLocation() to pass autoOpen=true to the target pages.

**Comment by MandeepPaul** [comment]
Passed the autoOpen prop using the useLocation hook and ensured the state is removed when the dialog is closed. 

It might also be necessary to remove the state during the onSave event. Please let me know if this is the expected behavior we want!

**Review by erenfn — APPROVED** [review]
Looks good!

**Comment by erenfn** [comment]
> Passed the autoOpen prop using the useLocation hook and ensured the state is removed when the dialog is closed.
> 
> It might also be necessary to remove the state during the onSave event. Please let me know if this is the expected behavior we want!

We are trying to fix that issue in #410, but thanks for pointing it out!

**Pull request merged**
