### PR TITLE
Toast.id type warning

### LINKED ISSUE #315: Toast.id type warning
`Warning: Failed prop type: Invalid prop `toast.id` of type `string` supplied to `ToastItem`, expected `number`. `

We sometimes encounter this warning. Changing the type from number to string doesn't resolve the issue, as we then receive a similar error: 'got number, expected string'.

 

- [ ] Identify where the problem occurs (check how we supply toast.id) and resolve the warning.

### PR DESCRIPTION
**Pull request by akshikrm**
Fixed the invalid prop issue. Issue was because of in ToastItem.PropTypes id was of the type number but the generated toast.id is a string.

closes #315

### CODE REVIEW

**Comment by erenfn** [comment]
This change will get rid of the warning but not fix the issue. We need to find out where this originates. We use the same lines of code to generate a toast notification, so that behavior is unexpected

**Comment by akshikrm** [comment]
I found out that in the **Toast** Component line number:13, the id is generated as a string and not a number as mentioned in the prop-types, this is where the issue is coming from.
```javascript

useEffect(() => {
....

>         id: `${Date.now()}-${Math.random()}`,

....
  }, []);
```
and if you take a look at **ToastItem.test.jsx** line:7 the id is a number, hence the test is passing without throwing any error.

```javascript

describe('ToastItem', () => {
....

>   const mockToast = { id: 1, message: 'Test Toast', duration: 1000 };

...

```
With the above findings the generated in the **Toast** component can be converted into a number type and it should fix the source of the issue.

**Comment by erenfn** [comment]
Then, I suppose we can just change it from a number to a string and update the tests accordingly. Could you also apply these changes?

**Review by erenfn — CHANGES_REQUESTED** [review]
Then, I suppose we can just change it from a number to a string and update the tests accordingly. Could you also apply these changes?

**Comment by erenfn** [comment]
Now I get this in tests:
```

stderr | src/tests/components/Toast/ToastItem.test.jsx > ToastItem > renders toast message correctly
Warning: Failed prop type: Invalid prop `toast.id` of type `number` supplied to `ToastItem`, expected `string`.
    at ToastItem (C:\Users\Eren\Documents\bluewave-onboarding\frontend\src\components\Toast\ToastItem.jsx:13:22)

```
Where do we supply type number?

**Review by uparkalau — APPROVED** [review]

**Review by uparkalau — CHANGES_REQUESTED** [review]
Update your branch from develop branch and open PR to the develop branch. @akshikrm

**Comment by erenfn** [comment]
Any updates?

**Pull request closed without merging**
