### PR TITLE
improve login page, forgot password page, sign up page ui and functionality

### PR DESCRIPTION
**Pull request by parthmanhas**
- change input field to CustomTextField to handle a bug in input field and sync design
- add loading indicator
- change to form to use built in validation for common error cases

Bug: 
image

Fix:

https://github.com/user-attachments/assets/458b655d-9f52-49b6-bba9-4967725559d0

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
Thank you @parthmanhas ! You can also remove all references to Google Auth in the auth screens, as this is planned to be deployed on a single server and the invitations are originated by the admin directly from within the dashboard. Therefore, there won't be 3rd party SSO planned for now.

**Comment by parthmanhas** [comment]
improve signup:

https://github.com/user-attachments/assets/38e15a92-0697-4643-963d-9d3985088294

**Comment by gorkem-bwl** [comment]
Looks good!

If I send you the logo, can you also change the current logo (which acts as a placeholder) with that one?

**Comment by parthmanhas** [comment]
> Looks good!
> 
> If I send you the logo, can you also change the current logo (which acts as a placeholder) with that one?

Please do !

**Review by uparkalau — APPROVED** [review]

**Comment by gorkem-bwl** [comment]
> > Looks good!
> > If I send you the logo, can you also change the current logo (which acts as a placeholder) with that one?
> 
> Please do !

I thought it would be best for you to decide the format of the logo. Here is the link to the corresponding Figma file where you can see the logo. You can download it any size and any format, and apply to login pages. Let me know if you need help and/or have any questions.

**Comment by parthmanhas** [comment]
Hi @gorkem-bwl, I added the logo svg and kept the dimensions are same as in figma file as I see it looks good. If you want any changes to it, please let me know !

image
image
image

**Comment by gorkem-bwl** [comment]
> Hi @gorkem-bwl, I added the logo svg and kept the dimensions are same as in figma file as I see it looks good. If you want any changes to it, please let me know !

No changes required. Thanks for this contribution!

**Comment by erenfn** [comment]
After you resolve the conflicts with develop branch and commit these changes again it is good to merge!

> Hi @gorkem-bwl, I added the logo svg and kept the dimensions are same as in figma file as I see it looks good. If you want any changes to it, please let me know !
> 
> image image image

**Pull request merged**
