### PR TITLE
56 implementing user logout functionalities

### PR DESCRIPTION
**Pull request by uparkalau**

### CODE REVIEW

**Comment by erenfn** [comment]
I was still able to add_popups (requires authentication) even though I logged out. Please take a look.

**Comment by uparkalau** [comment]
> I was still able to add_popups (requires authentication) even though I logged out. Please take a look.

Good point, I have to set an expiration time for token

**Comment by gorkem-bwl** [comment]
> > I was still able to add_popups (requires authentication) even though I logged out. Please take a look.
> 
> Good point, I have to set an expiration time for token

The token expiration time for uptime manager is 30 days when the user clicks on the 'remember me' button, and 2 hours otherwise: 

https://github.com/bluewave-labs/bluewave-uptime/issues/163

**Comment by uparkalau** [comment]
> I was still able to add_popups (requires authentication) even though I logged out. Please take a look.
This is because you don't check token during popup endpoints

**Pull request closed without merging**
