### PR TITLE
Moved Cancel and Save buttons positions to bottom

### PR DESCRIPTION
**Pull request by INDHU1402**
## Describe your changes

Moved Cancel and Save buttons positions to bottom in Create Hint Page while onboarding

## Issue number

Fixes the issue #370 

## Please ensure all items are checked off before requesting a review:

- [x] I have performed a self-review of my code.
- [x] I have included the issue # in the PR.
- [x] I have labelled the PR correctly.
- [x] My PR is granular and targeted to one specific feature only.

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
Can you please send a screenshot too?

**Comment by INDHU1402** [comment]
Sure @gorkem-bwl, after the change it looks like this.


Screenshot 2024-12-12 at 12 40 22 PM

**Comment by gorkem-bwl** [comment]
All the gaps here should be the same. Please fix the bottom gap and we're good to go!


image

**Comment by INDHU1402** [comment]
Hey @gorkem-bwl, fixed the bottom gap! (I assume this is what you meant)

Screenshot 2024-12-13 at 1 27 16 PM

**Comment by gorkem-bwl** [comment]
> Hey @gorkem-bwl, fixed the bottom gap! (I assume this is what you meant)

Please move the Cancel/Save buttons to this up to the purple line and we're done here!

image

**Comment by INDHU1402** [comment]
Sure, this is how it looks now.

Screenshot 2024-12-14 at 3 01 44 PM

@gorkem-bwl - Next time let's decide the final UI and then will do the change rather than hopping frequently

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl - Next time let's decide the final UI and then will do the change rather than hopping frequently

You are right - shouldn't have happened. Thanks for the heads up.

**Comment by erenfn** [comment]
It seems that this issue is already solved in #306 However, thank you for your time

**Comment by INDHU1402** [comment]
Cool, thanks for letting me know.
PS : If possible, please close all unnecessary issues so that it doesn't waste anyone's time in future.

**Pull request closed without merging**
