### PR TITLE
Feature/97 create a new customlink component

### PR DESCRIPTION
**Pull request by SimerdeepSinghGrewal**
Screenshot 2024-08-09 152335
 created custom Link component
created CustomLink.text.jsx component in tests
integrated the component in application where links are present.

### CODE REVIEW

**Comment by erenfn** [comment]
why are there 76 files changed?

**Comment by SimerdeepSinghGrewal** [comment]
> why are there 76 files changed?

That was due to the merge from develop branch that changed these files, I just accepted the changes from develop.

**Review by erenfn — CHANGES_REQUESTED** [review]
Links on the login pages should be our 'purple' color. 
Also there is also one more link in CreateAccountPage

Other than that, it is good to go

**Comment by SimerdeepSinghGrewal** [comment]
> Links on the login pages should be our 'purple' color. Also there is also one more link in CreateAccountPage
> 
> Other than that, it is good to go

done both

**Review by erenfn — APPROVED** [review]

**Pull request merged**
