### PR TITLE
convert new hint window to a popup/refactor HintDefaultPage

### PR DESCRIPTION
**Pull request by thomastepi**
- refactor HintDefaultPage - use existing template component
- convert the hint window to a modal pop-up - clicking the close icon now closes the pop-up and navigates back to the hint list page.

### CODE REVIEW

**Review by erenfn — CHANGES_REQUESTED** [review]
error during build:
[vite]: Rollup failed to resolve import "react-quill/dist/quill.snow.css" from "/home/runner/work/bluewave-onboarding/bluewave-onboarding/frontend/src/components/RichTextEditor/RichTextEditor.jsx".

This is what we get from Github Actions

**Comment by erenfn** [comment]
I get this in terminal:

[vite] Failed to load source map for /bluewave-onboarding/frontend/node_modules/react-quill-new/dist/quill.snow.css.
Error: An error occurred while trying to read the map file at quill.snow.css.map
Error: ENOENT: no such file or directory, open '\bluewave-onboarding\frontend\node_modules\react-quill-new\dist\quill.snow.css.map'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1238:14)

**Comment by thomastepi** [comment]
> I get this in terminal although I did npm install. Do you get this too?
> 
> [vite] Failed to load source map for /bluewave-onboarding/frontend/node_modules/react-quill-new/dist/quill.snow.css. Error: An error occurred while trying to read the map file at quill.snow.css.map Error: ENOENT: no such file or directory, open '\bluewave-onboarding\frontend\node_modules\react-quill-new\dist\quill.snow.css.map' at async open (node:internal/fs/promises:638:25) at async Object.readFile (node:internal/fs/promises:1238:14)

Yes, I encountered the same issue. It seems the react-quill-new package, which we’re using to avoid the deprecated findDOMNode api, doesn’t include a source map for the quill.snow.css file.

To work around this, I have decided to import the ReactQuill component from react-quill-new but kept the CSS import from the original react-quill package. This avoids the source map issue while still addressing the deprecated api problem.

**Review by uparkalau — APPROVED** [review]

**Comment by erenfn** [comment]
> > I get this in terminal although I did npm install. Do you get this too?
> > [vite] Failed to load source map for /bluewave-onboarding/frontend/node_modules/react-quill-new/dist/quill.snow.css. Error: An error occurred while trying to read the map file at quill.snow.css.map Error: ENOENT: no such file or directory, open '\bluewave-onboarding\frontend\node_modules\react-quill-new\dist\quill.snow.css.map' at async open (node:internal/fs/promises:638:25) at async Object.readFile (node:internal/fs/promises:1238:14)
> 
> Yes, I encountered the same issue. It seems the react-quill-new package, which we’re using to avoid the deprecated findDOMNode api, doesn’t include a source map for the quill.snow.css file.
> 
> To work around this, I have decided to import the ReactQuill component from react-quill-new but kept the CSS import from the original react-quill package. This avoids the source map issue while still addressing the deprecated api problem.

I still get that error. Did you push your changes?

**Pull request closed without merging**
