### PR TITLE
add color picker

### PR DESCRIPTION
**Pull request by parthmanhas**
https://github.com/user-attachments/assets/e43fd220-ceee-4ded-9a87-2be3b7334f5b

### CODE REVIEW

**Comment by parthmanhas** [comment]
fixes #217

**Review by erenfn — CHANGES_REQUESTED** [review]
Looks good! Can you change the borders so that it fits our design?

**Comment by parthmanhas** [comment]
Hi erenfn, looks like this now, the border-radius is same the existing one i.e 4px, changed padding and height to match existing styles
image

Existing styles 
image

**Comment by uparkalau** [comment]
Thank you for your contribution. Could you please merge the develop branch into your branch and then do a PR into the develop branch? We are testing the develop branch before merging it into the master.

**Comment by erenfn** [comment]
- The font styling is currently inherited from MUI's styles. It should be set as:

```
font-size: 13px;
color: var(--second-text-color);
```

and the other things shouldn't be inherited

- It would be better to remove the box shadow from the color picker to fit the design

- The value prop is not functioning as expected. Could you please take a look at that as well?

**Pull request closed without merging**
